---
- name: Deploy Real Estate Application
  hosts: real_estate
  become: yes

  vars:
    backend_dir: "/home/ubuntu/Dream-properties/Real Estate Backend/real-estate"
    frontend_build_dir: "/home/ubuntu/Dream-properties/real-estate-frontend/dist/real-estate-frontend/browser"
    backend_jar: "real-estate-0.0.1-SNAPSHOT.jar"
    backend_image: "real_estate_backend"
    frontend_image: "real_estate_frontend"

  tasks:
    - name: Ensure Docker and Nginx are installed
      apt:
        name:
          - docker.io
          - nginx
        state: present
        update_cache: yes

    - name: Stop and remove existing containers (if running)
      shell: |
        docker stop {{ backend_image }} 2>/dev/null || true
        docker rm {{ backend_image }} 2>/dev/null || true
      ignore_errors: yes

    - name: Clean and recreate Nginx web root
      file:
        path: /var/www/html
        state: absent
      ignore_errors: yes

    - name: Create Nginx web root directory
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy Angular build to Nginx directory
      copy:
        src: "{{ frontend_build_dir }}/"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'
      notify: Restart Nginx

    - name: Configure Nginx for Angular SPA
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;

              root /var/www/html;
              index index.html index.htm;

              server_name _;

              location / {
                  try_files $uri $uri/ /index.html;
              }

              location /api/ {
                  proxy_pass http://localhost:8080/;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
      notify: Restart Nginx

    - name: Build backend Docker image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        build:
          path: "{{ backend_dir }}"
        source: build

    - name: Run backend container
      community.docker.docker_container:
        name: "{{ backend_image }}"
        image: "{{ backend_image }}"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
        env:
          SPRING_PROFILES_ACTIVE: "prod"

    - name: Verify backend container is running
      shell: docker ps | grep {{ backend_image }}
      register: backend_status
      changed_when: false

    - debug:
        msg: "✅ Backend deployed successfully and running on port 8080"

    - name: Verify frontend (Angular + Nginx) is accessible
      uri:
        url: http://localhost
        return_content: yes
      register: frontend_response
      failed_when: "'Welcome to nginx!' in frontend_response.content"

    - debug:
        msg: "✅ Frontend deployed successfully and served by Nginx"

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
