---
- name: Deploy Real Estate Application on AWS EC2
  hosts: all
  become: yes

  vars:
    app_base: /home/ubuntu/Dream-properties
    backend_dir: "/home/ubuntu/Dream-properties/Real Estate Backend/real-estate"
    frontend_dir: /home/ubuntu/Dream-properties/real-estate-frontend
    frontend_build_path: /home/ubuntu/Dream-properties/real-estate-frontend/dist/real-estate-frontend/browser

  tasks:
    # --- System Setup ---
    - name: Update apt cache and install base packages
      apt:
        update_cache: yes
        name:
          - git
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
          - unzip
          - software-properties-common
          - apt-transport-https
          - nginx
        state: present

    # --- Install Java 21 ---
    - name: Install OpenJDK 21
      apt:
        name: openjdk-21-jdk
        state: present

    # --- Install Maven ---
    - name: Ensure Maven is installed
      apt:
        name: maven
        state: present

    # --- Install Docker ---
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    # --- Install Node.js 18.x ---
    - name: Install Node.js 18.x
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
      args:
        executable: /bin/bash

    # --- Clone Latest Code ---
    - name: Clone latest code from GitHub
      git:
        repo: "https://github.com/neharika005/Dream-properties.git"
        dest: "{{ app_base }}"
        version: main
        force: yes

    # --- Build Backend ---
    - name: Build backend using Maven
      shell: |
        cd "{{ backend_dir }}"
        mvn clean package -DskipTests
      args:
        executable: /bin/bash

    # --- Build Frontend ---
    - name: Build Angular frontend
      shell: |
        cd "{{ frontend_dir }}"
        npm install
        npm run build -- --configuration production
      args:
        executable: /bin/bash

    # --- Dockerize Backend ---
    - name: Stop old backend container if running
      shell: docker stop real_estate_backend || true && docker rm real_estate_backend || true
      args:
        executable: /bin/bash

    - name: Build backend Docker image
      shell: |
        cd "{{ backend_dir }}"
        docker build -t real_estate_backend .
      args:
        executable: /bin/bash

    - name: Run backend container
      shell: |
        docker run -d --name real_estate_backend -p 8080:8080 real_estate_backend
      args:
        executable: /bin/bash

    # --- Configure Nginx ---
    - name: Remove default Nginx site completely
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create Nginx configuration for Real Estate app
      copy:
        dest: /etc/nginx/sites-available/real_estate.conf
        content: |
          server {
              listen 80;
              server_name _;

              # API reverse proxy
              location /api/ {
                  proxy_pass http://127.0.0.1:8080/;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              # Angular frontend
              location / {
                  root {{ frontend_build_path }};
                  index index.html;
                  try_files $uri $uri/ /index.html;
              }
          }

    - name: Enable Real Estate site
      file:
        src: /etc/nginx/sites-available/real_estate.conf
        dest: /etc/nginx/sites-enabled/real_estate.conf
        state: link
        force: yes

    - name: Test Nginx configuration
      command: nginx -t

    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted
        enabled: yes

    # --- Verify that Angular is served (no longer strict content check) ---
    - name: Wait 5 seconds for Nginx reload
      wait_for:
        timeout: 5

    - name: Verify frontend served by Nginx
      uri:
        url: http://localhost
        return_content: yes
      register: frontend_check
      changed_when: false

    - debug:
        msg: "✅ Frontend loaded from Nginx. First 300 chars:\n{{ frontend_check.content[:300] }}"
