name: CI-CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Install Ansible and docker collection
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git
          pip3 install --user ansible
          export PATH="$HOME/.local/bin:$PATH"
          ansible-galaxy collection install community.docker

      - name: Prepare Ansible files
        run: |
          mkdir -p ansible
          cat > ansible/inventory <<EOF
[real_estate]
${{ secrets.EC2_HOST }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
EOF
          cat > ansible/ansible.cfg <<EOF
[defaults]
inventory = inventory
host_key_checking = False
EOF

      - name: Run Ansible deploy
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ansible-playbook -i ansible/inventory ansible/deploy.yml

